// Data: seznam cvikĹŻ pro partii â€žlĂ˝tkaâ€ś.

import { Exercise } from '@/src/data/types';

const CALVES: Exercise[] = [{ id: 'calves-1', name: 'Standing Calf Raise', equipment: 'Stroj/ÄŚinka', primaryMuscles: ['calves'], difficulty: 'easy', instructions: ['Postavte se na hranu stupĂ­nku/stroje tak, aby paty mohly jĂ­t dolĹŻ.', 'DrĹľte tÄ›lo rovnÄ› a zpevnÄ›te bĹ™icho.', 'SpusĹĄte paty dolĹŻ do protaĹľenĂ­ lĂ˝tek.', 'ZvednÄ›te se co nejvĂ˝Ĺˇ na ĹˇpiÄŤky a nahoĹ™e krĂˇtce zatnÄ›te.', 'Pomalu se vraĹĄte dolĹŻ â€“ bez odrazĹŻ.', 'UdrĹľujte rovnomÄ›rnĂ© tempo v celĂ©m rozsahu.'] },
  { id: 'calves-2', name: 'Seated Calf Raise', equipment: 'Stroj', primaryMuscles: ['calves'], difficulty: 'easy', instructions: ['SednÄ›te si do stroje a chodidla poloĹľte na platformu.', 'Kolena dejte pod opÄ›rku a drĹľte zĂˇda vzpĹ™Ă­menÄ›.', 'SpusĹĄte paty dolĹŻ do protaĹľenĂ­.', 'VytlaÄŤte ĹˇpiÄŤky nahoru do maximĂˇlnĂ­ kontrakce.', 'NahoĹ™e krĂˇtce vydrĹľte a pomalu spouĹˇtÄ›jte zpÄ›t.', 'Nehoupejte se tÄ›lem â€“ pracujĂ­ jen kotnĂ­ky.'] },
  { id: 'calves-3', name: 'Donkey Calf Raise', equipment: 'Stroj', primaryMuscles: ['calves'], difficulty: 'medium', instructions: ['ZaujmÄ›te pozici v donkey stroji (nebo v pĹ™edklonu s oporou).', 'DrĹľte rovnĂˇ zĂˇda a zpevnÄ›nĂ© bĹ™icho.', 'SpusĹĄte paty dolĹŻ do protaĹľenĂ­ lĂ˝tek.', 'ZvednÄ›te se na ĹˇpiÄŤky co nejvĂ˝Ĺˇ a nahoĹ™e zatnÄ›te.', 'Pomalu spouĹˇtÄ›jte dolĹŻ bez â€žpruĹľenĂ­â€ś.', 'DrĹľte kontrolu a plynulĂ˝ rozsah.'] },
  { id: 'calves-4', name: 'Jump Rope', equipment: 'Ĺ vihadlo', primaryMuscles: ['calves'], difficulty: 'easy', instructions: ['Nastavte dĂ©lku Ĺˇvihadla a drĹľte lokty u tÄ›la.', 'SkĂˇkejte nĂ­zko â€“ jen pĂˇr centimetrĹŻ nad zem.', 'Dopadejte mÄ›kce na pĹ™ednĂ­ ÄŤĂˇst chodidla a paty nechte lehce nad zemĂ­.', 'UdrĹľujte rovnĂ˝ trup a plynulĂ© dĂ˝chĂˇnĂ­.', 'ZaÄŤnÄ›te kratĹˇĂ­mi intervaly a postupnÄ› pĹ™idĂˇvejte ÄŤas.', 'KdyĹľ ztrĂˇcĂ­te rytmus, zpomalte a zkraĹĄte skoky.'] },
  { id: 'calves-5', name: 'Calf Press on Leg Press', equipment: 'Stroj', primaryMuscles: ['calves'], difficulty: 'medium', instructions: ['Nastavte leg press a chodidla dejte na spodnĂ­ ÄŤĂˇst platformy.', 'Kolena drĹľte lehce pokrÄŤenĂˇ a zafixujte pĂˇnev v sedu.', 'SpusĹĄte paty dolĹŻ (platforma se pohne jen pĹ™es kotnĂ­ky).', 'VytlaÄŤte ĹˇpiÄŤky nahoru do plnĂ© kontrakce lĂ˝tek.', 'Pomalu se vraĹĄte do protaĹľenĂ­ bez odrazu.', 'Nezamykajte kolena a neodrĂˇĹľejte se.'] },
  { id: 'calves-6', name: 'Calves Builder 6', equipment: 'Stroj', primaryMuscles: ['calves'], difficulty: 'easy', instructions: ['Nastavte vychozi pozici stroje.', 'Provadejte kontrolovany pohyb v plnem rozsahu.', 'Vracejte se pomalu bez trhani.', 'Drzte stabilni trup a plynuly dech.'] },
  { id: 'calves-7', name: 'Calves Focus 7', equipment: 'Jednorucky', primaryMuscles: ['calves'], difficulty: 'medium', instructions: ['Zvolte primerenou zatez pro cisty pohyb.', 'Provedte koncentrickou fazi s vydechem.', 'Excentrickou fazi zpomalte na 2 az 3 sekundy.', 'Po celou dobu drzte techniku bez kompenzaci.'] },
  { id: 'calves-8', name: 'Calves Builder 8', equipment: 'Stroj', primaryMuscles: ['calves'], difficulty: 'easy', instructions: ['Nastavte vychozi pozici.', 'Provadejte kontrolovany pohyb.', 'Vracejte se pomalu bez trhani.', 'Drzte stabilni trup a plynuly dech.'] },
  { id: 'calves-9', name: 'Calves Builder 9', equipment: 'Jednorucky', primaryMuscles: ['calves'], difficulty: 'medium', instructions: ['Nastavte vychozi pozici.', 'Provadejte kontrolovany pohyb.', 'Vracejte se pomalu bez trhani.', 'Drzte stabilni trup a plynuly dech.'] },
];

export default CALVES;

