// Data: seznam cvikĹŻ pro partii â€žhrudnĂ­kâ€ś.

import { Exercise } from '@/src/data/types';

const CHEST: Exercise[] = [{ id: 'chest-1', name: 'Bench Press', equipment: 'ÄŚinka, lavice', primaryMuscles: ['chest'], difficulty: 'medium', instructions: ['LehnÄ›te si na laviÄŤku, chodidla pevnÄ› na zemi a lopatky stĂˇhnÄ›te k sobÄ›.', 'Uchopte osu o nÄ›co ĹˇirĹˇĂ­ neĹľ ramena a drĹľte zĂˇpÄ›stĂ­ rovnÄ›.', 'S nĂˇdechem spusĹĄte ÄŤinku kontrolovanÄ› na stĹ™ed hrudnĂ­ku.', 'S vĂ˝dechem vytlaÄŤte ÄŤinku nahoru a drĹľte lokty pod osou.', 'NeodrĂˇĹľejte ÄŤinku od hrudnĂ­ku a neprohĂ˝bejte se zbyteÄŤnÄ› v bedrech.', 'VĹľdy uklĂˇdejte ÄŤinku bezpeÄŤnÄ› do stojanu.'] },
  { id: 'chest-2', name: 'Incline Dumbbell Press', equipment: 'JednoruÄŤky, lavice', primaryMuscles: ['chest'], difficulty: 'medium', instructions: ['Nastavte Ĺˇikmou lavici (cca 30â€“45Â°) a opĹ™ete zĂˇda i hlavu.', 'ZvednÄ›te jednoruÄŤky do ĂşrovnÄ› ramen, lokty mĂ­rnÄ› pod ĂşrovnĂ­ ramen.', 'S vĂ˝dechem tlaÄŤte jednoruÄŤky nahoru a lehce k sobÄ› (bez tvrdĂ©ho â€žklepnutĂ­â€ś).', 'KontrolovanÄ› spouĹˇtÄ›jte zpÄ›t dolĹŻ do protaĹľenĂ­ hrudnĂ­ku.', 'DrĹľte lopatky staĹľenĂ© a ramena dole po celou dobu.', 'NeprohĂ˝bejte se a nepouĹľĂ­vejte Ĺˇvih.'] },
  { id: 'chest-3', name: 'Push-ups', equipment: 'VlastnĂ­ vĂˇha', primaryMuscles: ['chest'], difficulty: 'easy', instructions: ['Dejte dlanÄ› pod ramena (nebo trochu ĹˇirĹˇĂ­) a zaujmÄ›te pozici prkna.', 'ZpevnÄ›te bĹ™icho a hĂ˝ĹľdÄ›, tÄ›lo drĹľte v jednĂ© linii.', 'SpouĹˇtÄ›jte se dolĹŻ, lokty veÄŹte Ĺˇikmo dozadu (cca 30â€“60Â° od trupu).', 'DostaĹte hrudnĂ­k blĂ­zko k zemi bez prohnutĂ­ v bedrech.', 'VytlaÄŤte se zpÄ›t nahoru s vĂ˝dechem do plnĂ©ho propnutĂ­.', 'Pro lehÄŤĂ­ variantu dejte ruce vĂ˝Ĺˇ (o laviÄŤku/stĹŻl).'] },
  { id: 'chest-4', name: 'Cable Flyes', equipment: 'Kladka', primaryMuscles: ['chest'], difficulty: 'easy', instructions: ['Nastavte kladky zhruba do vĂ˝Ĺˇky ramen a chyĹĄte madla.', 'Postavte se do mĂ­rnĂ©ho kroku a lehce se pĹ™edkloĹte.', 'Lokty drĹľte mĂ­rnÄ› pokrÄŤenĂ© a ramena dole.', 'PĹ™itĂˇhnÄ›te ruce pĹ™ed tÄ›lo a spojte je pĹ™ed hrudnĂ­kem.', 'KrĂˇtce zatnÄ›te hrudnĂ­k a pomalu vraĹĄte ruce zpÄ›t do protaĹľenĂ­.', 'NevytĂˇÄŤejte ramena dopĹ™edu â€“ drĹľte lopatky stabilnÄ›.'] },
  { id: 'chest-5', name: 'Dips', equipment: 'ParalelnĂ­ bradla', primaryMuscles: ['chest', 'triceps'], difficulty: 'medium', instructions: ['ChyĹĄte bradla a zvednÄ›te se do opory s propnutĂ˝mi paĹľemi.', 'Pro variantu na hrudnĂ­k se lehce pĹ™edkloĹte a lokty veÄŹte Ĺˇikmo ven.', 'SpouĹˇtÄ›jte se dolĹŻ kontrolovanÄ›, dokud jsou paĹľe zhruba rovnobÄ›ĹľnÄ› se zemĂ­.', 'Zastavte dĹ™Ă­v, pokud cĂ­tĂ­te nepĹ™Ă­jemnĂ˝ tlak v ramenou.', 'VytlaÄŤte se zpÄ›t nahoru s vĂ˝dechem bez trhĂˇnĂ­.', 'UdrĹľujte lopatky dole a krk dlouhĂ˝.'] },
  { id: 'chest-6', name: 'Incline Barbell Press', equipment: 'ÄŚinka, ĹˇikmĂˇ lavice', primaryMuscles: ['chest'], difficulty: 'medium', instructions: ['Nastavte lavici na sklon 30 aĹľ 45 stupĹĹŻ.', 'SpusĹĄte osu kontrolovanÄ› na hornĂ­ ÄŤĂˇst hrudnĂ­ku.', 'VytlaÄŤte ÄŤinku nahoru bez Ĺˇvihu.', 'DrĹľte lopatky staĹľenĂ© a nohy pevnÄ› na zemi.'] },
  { id: 'chest-7', name: 'Decline Bench Press', equipment: 'ÄŚinka, negativnĂ­ lavice', primaryMuscles: ['chest'], difficulty: 'medium', instructions: ['BezpeÄŤnÄ› fixujte nohy na lavici.', 'SpouĹˇtÄ›jte osu k dolnĂ­ ÄŤĂˇsti hrudnĂ­ku.', 'TlaÄŤte plynule do propnutĂ­ paĹľĂ­.', 'NepĹ™etÄ›Ĺľujte ramena ani zĂˇpÄ›stĂ­.'] },
  { id: 'chest-8', name: 'Machine Chest Press', equipment: 'Stroj', primaryMuscles: ['chest'], difficulty: 'easy', instructions: ['Nastavte sedadlo tak, aby madla byla v Ăşrovni stĹ™edu hrudnĂ­ku.', 'TlaÄŤte madla vpĹ™ed s vĂ˝dechem.', 'Vracejte pomalu do vĂ˝chozĂ­ polohy.', 'Neodlepujte zĂˇda od opÄ›rky.'] },
  { id: 'chest-9', name: 'Dumbbell Fly', equipment: 'JednoruÄŤky, lavice', primaryMuscles: ['chest'], difficulty: 'easy', instructions: ['LehnÄ›te si na laviÄŤku s jednoruÄŤkami nad hrudnĂ­kem.', 'S mĂ­rnÄ› pokrÄŤenĂ˝mi lokty spouĹˇtÄ›jte paĹľe do stran.', 'V dolnĂ­ pozici cĂ­tĂ­te protaĹľenĂ­ hrudnĂ­ku.', 'VraĹĄte ÄŤinky zpÄ›t obloukem nad hrudnĂ­k.'] },
];

export default CHEST;

