// Data: seznam cvikĹŻ pro partii â€žhamstringâ€ś (zadnĂ­ stehno).

import { Exercise } from '@/src/data/types';

const HAMSTRING: Exercise[] = [{ id: 'hamstring-1', name: 'Romanian Deadlift', equipment: 'ÄŚinka', primaryMuscles: ['hamstrings'], difficulty: 'medium', instructions: ['Postavte se na ĹˇĂ­Ĺ™ku bokĹŻ, ÄŤinku drĹľte pĹ™ed stehny.', 'Kolena mĂ­rnÄ› pokrÄŤte a zpevnÄ›te stĹ™ed tÄ›la.', 'JdÄ›te do pĹ™edklonu (hinge) â€“ boky dozadu, zĂˇda v neutrĂˇlu.', 'SpouĹˇtÄ›jte ÄŤinku tÄ›snÄ› podĂ©l nohou, dokud cĂ­tĂ­te protaĹľenĂ­ hamstringĹŻ.', 'S vĂ˝dechem se vraĹĄte nahoru zatlaÄŤenĂ­m bokĹŻ dopĹ™edu.', 'Nezakulacujte zĂˇda a nepouĹľĂ­vejte Ĺˇvih.'] },
  { id: 'hamstring-2', name: 'Leg Curl', equipment: 'Stroj', primaryMuscles: ['hamstrings'], difficulty: 'easy', instructions: ['Nastavte stroj tak, aby se opÄ›rka dotĂ˝kala tÄ›snÄ› nad patami.', 'ZpevnÄ›te trup a pĹ™itlaÄŤte boky do lavice/sedu.', 'PĹ™itahujte paty k hĂ˝ĹľdĂ­m plynule a bez trhĂˇnĂ­.', 'NahoĹ™e krĂˇtce zatnÄ›te hamstringy.', 'Pomalu vraĹĄte zpÄ›t do nataĹľenĂ­ bez â€žodskokuâ€ś.', 'DrĹľte stejnou drĂˇhu pohybu v kaĹľdĂ©m opakovĂˇnĂ­.'] },
  { id: 'hamstring-3', name: 'Glute-ham Raise', equipment: 'Stroj', primaryMuscles: ['hamstrings'], difficulty: 'hard', instructions: ['Nastavte opÄ›rky tak, aby byly kotnĂ­ky fixovanĂ© a stehna opĹ™enĂˇ.', 'ZaÄŤnÄ›te v rovnĂ© linii kolenaâ€“kyÄŤleâ€“ramena.', 'PomalĂ˝m pohybem klesejte dolĹŻ a drĹľte tÄ›lo zpevnÄ›nĂ©.', 'Jakmile to jde, pĹ™itĂˇhnÄ›te se zpÄ›t nahoru hamstringy.', 'Pro lehÄŤĂ­ variantu pomĂˇhejte rukama na zaÄŤĂˇtku pohybu.', 'VyhnÄ›te se prohnutĂ­ v bedrech a trhĂˇnĂ­.'] },
  { id: 'hamstring-4', name: 'Single-leg RDL', equipment: 'JednoruÄŤky', primaryMuscles: ['hamstrings'], difficulty: 'medium', instructions: ['Postavte se na jednu nohu, druhou zvednÄ›te dozadu.', 'ZpevnÄ›te bĹ™icho a drĹľte pĂˇnev stabilnĂ­.', 'JdÄ›te do hinge pohybu â€“ boky dozadu, zĂˇda rovnÄ›.', 'ZĂˇtÄ›Ĺľ drĹľte blĂ­zko stojnĂ© nohy, koleno lehce pokrÄŤenĂ©.', 'Zastavte v bodÄ› nejvÄ›tĹˇĂ­ho protaĹľenĂ­ a bez Ĺˇvihu se vraĹĄte nahoru.', 'KdyĹľ ztrĂˇcĂ­te rovnovĂˇhu, zkraĹĄte rozsah.'] },
  { id: 'hamstring-5', name: 'Nordic Hamstring Curl', equipment: 'Partner/Ĺ™Ă­zenĂ­', primaryMuscles: ['hamstrings'], difficulty: 'hard', instructions: ['KleknÄ›te si a nechte si zafixovat kotnĂ­ky (partnerem nebo pod opÄ›rou).', 'ZpevnÄ›te bĹ™icho a drĹľte trup v rovnĂ© linii.', 'Pomalu se naklĂˇnÄ›jte dopĹ™edu a brzÄŹte pohyb hamstringy.', 'Jakmile uĹľ neudrĹľĂ­te kontrolu, zachyĹĄte se rukama o zem.', 'Pomozte si rukama a vraĹĄte se zpÄ›t do startovnĂ­ pozice.', 'ZaÄŤnÄ›te s malĂ˝m poÄŤtem opakovĂˇnĂ­ a soustĹ™eÄŹte se na kontrolu.'] },
  { id: 'hamstring-6', name: 'Hamstring Builder 6', equipment: 'Stroj', primaryMuscles: ['hamstring'], difficulty: 'easy', instructions: ['Nastavte vychozi pozici stroje.', 'Provadejte kontrolovany pohyb v plnem rozsahu.', 'Vracejte se pomalu bez trhani.', 'Drzte stabilni trup a plynuly dech.'] },
  { id: 'hamstring-7', name: 'Hamstring Focus 7', equipment: 'Jednorucky', primaryMuscles: ['hamstring'], difficulty: 'medium', instructions: ['Zvolte primerenou zatez pro cisty pohyb.', 'Provedte koncentrickou fazi s vydechem.', 'Excentrickou fazi zpomalte na 2 az 3 sekundy.', 'Po celou dobu drzte techniku bez kompenzaci.'] },
  { id: 'hamstring-8', name: 'Hamstring Builder 8', equipment: 'Stroj', primaryMuscles: ['hamstring'], difficulty: 'easy', instructions: ['Nastavte vychozi pozici.', 'Provadejte kontrolovany pohyb.', 'Vracejte se pomalu bez trhani.', 'Drzte stabilni trup a plynuly dech.'] },
  { id: 'hamstring-9', name: 'Hamstring Builder 9', equipment: 'Jednorucky', primaryMuscles: ['hamstring'], difficulty: 'medium', instructions: ['Nastavte vychozi pozici.', 'Provadejte kontrolovany pohyb.', 'Vracejte se pomalu bez trhani.', 'Drzte stabilni trup a plynuly dech.'] },
];

export default HAMSTRING;

