// Data: seznam cvikĹŻ pro partii â€žpĹ™edloktĂ­â€ś.

import { Exercise } from '@/src/data/types';

const FOREARM: Exercise[] = [{ id: 'forearm-1', name: 'Wrist Curls', equipment: 'ÄŚinka', primaryMuscles: ['forearm'], difficulty: 'easy', instructions: ['SednÄ›te si a pĹ™edloktĂ­ opĹ™ete o stehna nebo laviÄŤku, dlanÄ› smÄ›Ĺ™ujĂ­ nahoru.', 'ÄŚinku drĹľte lehce v prstech a nechte zĂˇpÄ›stĂ­ klesnout do protaĹľenĂ­.', 'Zvedejte zĂˇpÄ›stĂ­ nahoru bez pohybu v lokti.', 'NahoĹ™e krĂˇtce zatnÄ›te pĹ™edloktĂ­.', 'Pomalu spusĹĄte zpÄ›t dolĹŻ do plnĂ©ho rozsahu.', 'PouĹľijte lehkou vĂˇhu a dÄ›lejte plynulĂ© opakovĂˇnĂ­.'] },
  { id: 'forearm-2', name: 'Reverse Wrist Curls', equipment: 'ÄŚinka', primaryMuscles: ['forearm'], difficulty: 'easy', instructions: ['SednÄ›te si a pĹ™edloktĂ­ opĹ™ete o stehna/laviÄŤku, dlanÄ› smÄ›Ĺ™ujĂ­ dolĹŻ.', 'Nechte zĂˇpÄ›stĂ­ klesnout dolĹŻ do protaĹľenĂ­.', 'Zvedejte hĹ™bet ruky nahoru (pohyb jde jen ze zĂˇpÄ›stĂ­).', 'NahoĹ™e krĂˇtce zatnÄ›te a drĹľte kontrolu.', 'Pomalu vraĹĄte zpÄ›t dolĹŻ.', 'DrĹľte lokty fixovanĂ© a nepouĹľĂ­vejte Ĺˇvih.'] },
  { id: 'forearm-3', name: "Farmer's Walk", equipment: 'ÄŚinka/JednoruÄŤky', primaryMuscles: ['forearm'], difficulty: 'medium', instructions: ['VezmÄ›te do rukou jednoruÄŤky nebo trap bar a postavte se rovnÄ›.', 'ZpevnÄ›te bĹ™icho, stĂˇhnÄ›te ramena dolĹŻ a drĹľte dlouhĂ˝ krk.', 'ZaÄŤnÄ›te chodit krĂˇtkĂ˝mi stabilnĂ­mi kroky bez houpĂˇnĂ­ tÄ›lem.', 'DrĹľte Ăşchop pevnĂ˝, ale nekrÄŤte ramena k uĹˇĂ­m.', 'OtoÄŤte se kontrolovanÄ› a pokraÄŤujte do cĂ­lovĂ© vzdĂˇlenosti/ÄŤasu.', 'UkonÄŤete sĂ©rii, kdyĹľ se zaÄŤne hroutit drĹľenĂ­ tÄ›la.'] },
  { id: 'forearm-4', name: 'Towel Pull-ups', equipment: 'Hrazda + ruÄŤnĂ­k', primaryMuscles: ['forearm','biceps'], difficulty: 'hard', instructions: ['PĹ™ehoÄŹte ruÄŤnĂ­k pĹ™es hrazdu a chyĹĄte oba konce (nebo dva ruÄŤnĂ­ky).', 'PovÄ›ste se do visu a aktivujte ramena staĹľenĂ­m lopatek dolĹŻ.', 'TĂˇhnÄ›te nahoru jako u shybĹŻ â€“ lokty veÄŹte dolĹŻ k bokĹŻm.', 'NahoĹ™e krĂˇtce zastavte a drĹľte tÄ›lo bez houpĂˇnĂ­.', 'Pomalu se spusĹĄte zpÄ›t do visu.', 'Pokud je to moc tÄ›ĹľkĂ©, pouĹľijte gumu nebo zkraĹĄte rozsah.'] },
  { id: 'forearm-5', name: 'Plate Pinches', equipment: 'ZĂˇvaĹľĂ­', primaryMuscles: ['forearm'], difficulty: 'easy', instructions: ['VezmÄ›te kotouÄŤe a chyĹĄte je mezi palec a prsty (pinch grip).', 'Postavte se rovnÄ› a drĹľte ramena dole.', 'DrĹľte kotouÄŤe po stanovenĂ˝ ÄŤas bez ohĂ˝bĂˇnĂ­ zĂˇpÄ›stĂ­.', 'DĂ˝chejte plynule a neprohĂ˝bejte se v bedrech.', 'OdloĹľte a dejte pauzu, potĂ© opakujte na dalĹˇĂ­ sĂ©rii.', 'ZaÄŤnÄ›te lehÄŤĂ­ vĂˇhou a postupnÄ› pĹ™idĂˇvejte.'] },
  { id: 'forearm-6', name: 'Forearm Builder 6', equipment: 'Stroj', primaryMuscles: ['forearm'], difficulty: 'easy', instructions: ['Nastavte vychozi pozici stroje.', 'Provadejte kontrolovany pohyb v plnem rozsahu.', 'Vracejte se pomalu bez trhani.', 'Drzte stabilni trup a plynuly dech.'] },
  { id: 'forearm-7', name: 'Forearm Focus 7', equipment: 'Jednorucky', primaryMuscles: ['forearm'], difficulty: 'medium', instructions: ['Zvolte primerenou zatez pro cisty pohyb.', 'Provedte koncentrickou fazi s vydechem.', 'Excentrickou fazi zpomalte na 2 az 3 sekundy.', 'Po celou dobu drzte techniku bez kompenzaci.'] },
  { id: 'forearm-8', name: 'Forearm Builder 8', equipment: 'Stroj', primaryMuscles: ['forearm'], difficulty: 'easy', instructions: ['Nastavte vychozi pozici.', 'Provadejte kontrolovany pohyb.', 'Vracejte se pomalu bez trhani.', 'Drzte stabilni trup a plynuly dech.'] },
  { id: 'forearm-9', name: 'Forearm Builder 9', equipment: 'Jednorucky', primaryMuscles: ['forearm'], difficulty: 'medium', instructions: ['Nastavte vychozi pozici.', 'Provadejte kontrolovany pohyb.', 'Vracejte se pomalu bez trhani.', 'Drzte stabilni trup a plynuly dech.'] },
];

export default FOREARM;

