// Data: seznam cvikĹŻ pro partii â€žramenaâ€ś (deltoids).

import { Exercise } from '@/src/data/types';

const DELTOIDS: Exercise[] = [{ id: 'deltoids-1', name: 'Overhead Press', equipment: 'ÄŚinka', primaryMuscles: ['deltoids'], difficulty: 'medium', instructions: ['Postavte se na ĹˇĂ­Ĺ™ku bokĹŻ a ÄŤinku drĹľte v Ăşrovni klĂ­ÄŤnĂ­ch kostĂ­.', 'ZpevnÄ›te bĹ™icho a hĂ˝ĹľdÄ›, Ĺľebra drĹľte â€ždoleâ€ś.', 'S vĂ˝dechem tlaÄŤte ÄŤinku pĹ™Ă­mo nad hlavu a hlavu lehce posuĹte dopĹ™edu pod osu.', 'NahoĹ™e drĹľte lokty plnÄ› propnutĂ© bez pĹ™ehnanĂ©ho prohnutĂ­ v bedrech.', 'KontrolovanÄ› spouĹˇtÄ›jte ÄŤinku zpÄ›t na ramena.', 'Pokud vĂˇs bolĂ­ ramena, zkraĹĄte rozsah nebo sniĹľte vĂˇhu.'] },
  { id: 'deltoids-2', name: 'Lateral Raises', equipment: 'JednoruÄŤky', primaryMuscles: ['deltoids'], difficulty: 'easy', instructions: ['Postavte se rovnÄ›, jednoruÄŤky drĹľte u stehen a lokty mĂ­rnÄ› pokrÄŤte.', 'ZpevnÄ›te stĹ™ed tÄ›la a drĹľte ramena dole (nekrÄŤte je k uĹˇĂ­m).', 'Zvedejte ruce do stran aĹľ do ĂşrovnÄ› ramen â€“ lokty lehce vĂ˝Ĺˇ neĹľ zĂˇpÄ›stĂ­.', 'NahoĹ™e krĂˇtce zastavte bez Ĺˇvihu.', 'Pomalu spouĹˇtÄ›jte dolĹŻ do vĂ˝chozĂ­ pozice.', 'PouĹľijte menĹˇĂ­ vĂˇhu a ÄŤistou techniku.'] },
  { id: 'deltoids-3', name: 'Front Raises', equipment: 'JednoruÄŤky', primaryMuscles: ['deltoids'], difficulty: 'easy', instructions: ['Postavte se rovnÄ› a drĹľte jednoruÄŤky pĹ™ed stehny.', 'ZpevnÄ›te bĹ™icho a drĹľte lopatky stabilnÄ›.', 'Zvedejte jednoruÄŤky pĹ™ed sebe do ĂşrovnÄ› ramen (bez prohnutĂ­ v bedrech).', 'Lokty drĹľte mĂ­rnÄ› pokrÄŤenĂ© a zĂˇpÄ›stĂ­ rovnÄ›.', 'Pomalu spouĹˇtÄ›jte zpÄ›t dolĹŻ a drĹľte kontrolu.', 'Pro lepĹˇĂ­ kontrolu mĹŻĹľete stĹ™Ă­dat ruce.'] },
  { id: 'deltoids-4', name: 'Reverse Flyes', equipment: 'JednoruÄŤky', primaryMuscles: ['rear-delts'], difficulty: 'easy', instructions: ['JdÄ›te do pĹ™edklonu s rovnĂ˝mi zĂˇdy (hinge) nebo se opĹ™ete o lavici.', 'JednoruÄŤky nechte viset pod rameny, lokty mĂ­rnÄ› pokrÄŤte.', 'RozpaĹľujte do stran a lokty veÄŹte do ĂşrovnÄ› ramen.', 'NahoĹ™e stĂˇhnÄ›te lopatky jemnÄ› k sobÄ› (bez pĹ™etahovĂˇnĂ­).', 'Pomalu vraĹĄte dolĹŻ do vĂ˝chozĂ­ pozice.', 'NedÄ›lejte Ĺˇvih â€“ radÄ›ji sniĹľte vĂˇhu.'] },
  { id: 'deltoids-5', name: 'Arnold Press', equipment: 'JednoruÄŤky', primaryMuscles: ['deltoids'], difficulty: 'medium', instructions: ['SednÄ›te si nebo stĹŻjte, jednoruÄŤky drĹľte pĹ™ed obliÄŤejem, dlanÄ› k sobÄ›.', 'ZpevnÄ›te stĹ™ed tÄ›la a drĹľte ramena dole.', 'PĹ™i tlaku nahoru otĂˇÄŤejte dlanÄ›mi ven, aĹľ jsou v hornĂ­ pozici dopĹ™edu.', 'NahoĹ™e drĹľte lokty propnutĂ© a kontrolujte bedra.', 'PĹ™i spouĹˇtÄ›nĂ­ dolĹŻ otĂˇÄŤejte zpÄ›t do startovnĂ­ pozice.', 'Pohyb je plynulĂ˝ â€“ bez trhĂˇnĂ­ a bez Ĺˇvihu.'] },
  { id: 'deltoids-6', name: 'Deltoids Builder 6', equipment: 'Stroj', primaryMuscles: ['deltoids'], difficulty: 'easy', instructions: ['Nastavte vychozi pozici stroje.', 'Provadejte kontrolovany pohyb v plnem rozsahu.', 'Vracejte se pomalu bez trhani.', 'Drzte stabilni trup a plynuly dech.'] },
  { id: 'deltoids-7', name: 'Deltoids Focus 7', equipment: 'Jednorucky', primaryMuscles: ['deltoids'], difficulty: 'medium', instructions: ['Zvolte primerenou zatez pro cisty pohyb.', 'Provedte koncentrickou fazi s vydechem.', 'Excentrickou fazi zpomalte na 2 az 3 sekundy.', 'Po celou dobu drzte techniku bez kompenzaci.'] },
  { id: 'deltoids-8', name: 'Deltoids Builder 8', equipment: 'Stroj', primaryMuscles: ['deltoids'], difficulty: 'easy', instructions: ['Nastavte vychozi pozici.', 'Provadejte kontrolovany pohyb.', 'Vracejte se pomalu bez trhani.', 'Drzte stabilni trup a plynuly dech.'] },
  { id: 'deltoids-9', name: 'Deltoids Builder 9', equipment: 'Jednorucky', primaryMuscles: ['deltoids'], difficulty: 'medium', instructions: ['Nastavte vychozi pozici.', 'Provadejte kontrolovany pohyb.', 'Vracejte se pomalu bez trhani.', 'Drzte stabilni trup a plynuly dech.'] },
];

export default DELTOIDS;

