// Data: seznam cvikĹŻ pro partii â€žbicepsâ€ś.

import { Exercise } from '@/src/data/types';

const BICEPS: Exercise[] = [{ id: 'biceps-1', name: 'Barbell Curls', equipment: 'ÄŚinka', primaryMuscles: ['biceps'], difficulty: 'medium', instructions: ['Postavte se rovnÄ›, chodidla na ĹˇĂ­Ĺ™ku bokĹŻ a ÄŤinku drĹľte podhmatem.', 'ZpevnÄ›te bĹ™icho a drĹľte lokty u tÄ›la.', 'Zvedejte ÄŤinku nahoru pouze ohybem v loktech â€“ bez Ĺˇvihu trupem.', 'NahoĹ™e krĂˇtce zatnÄ›te biceps a drĹľte zĂˇpÄ›stĂ­ v neutrĂˇlu.', 'Pomalu spouĹˇtÄ›jte dolĹŻ aĹľ do nataĹľenĂ­ (bez â€žodskokuâ€ś).', 'KdyĹľ musĂ­te houpat, sniĹľte vĂˇhu.'] },
  { id: 'biceps-2', name: 'Dumbbell Hammer Curls', equipment: 'JednoruÄŤky', primaryMuscles: ['biceps','forearm'], difficulty: 'easy', instructions: ['Postavte se a drĹľte jednoruÄŤky neutrĂˇlnÄ› (dlanÄ› k sobÄ›).', 'ZpevnÄ›te stĹ™ed tÄ›la a drĹľte ramena dole.', 'Zvedejte jednoruÄŤky k ramenĹŻm, lokty zĹŻstĂˇvajĂ­ u tÄ›la.', 'NahoĹ™e krĂˇtce zatnÄ›te a nechte pĹ™edloktĂ­ stĂˇle v neutrĂˇlu.', 'PomalĂ˝m pohybem vraĹĄte zpÄ›t dolĹŻ do nataĹľenĂ­.', 'StĹ™Ă­dejte ruce nebo dÄ›lejte obÄ› najednou â€“ bez Ĺˇvihu.'] },
  { id: 'biceps-3', name: 'Concentration Curls', equipment: 'JednoruÄŤky', primaryMuscles: ['biceps'], difficulty: 'easy', instructions: ['SednÄ›te si, loket opĹ™ete o vnitĹ™nĂ­ stranu stehna.', 'Ruku nechte volnÄ› nataĹľenou dolĹŻ a zpevnÄ›te rameno (nepohybujte s nĂ­m).', 'Zvedejte jednoruÄŤku nahoru kontrolovanÄ›, bez odlepenĂ­ lokte z opory.', 'NahoĹ™e krĂˇtce zatnÄ›te biceps a drĹľte zĂˇpÄ›stĂ­ rovnÄ›.', 'Pomalu spouĹˇtÄ›jte zpÄ›t dolĹŻ do nataĹľenĂ­.', 'Pro jistotu jeÄŹte menĹˇĂ­ vĂˇhu a ÄŤistou techniku.'] },
  { id: 'biceps-4', name: 'Preacher Curls', equipment: 'Lavice', primaryMuscles: ['biceps'], difficulty: 'medium', instructions: ['Nastavte preacher lavici tak, aby paĹľe pohodlnÄ› leĹľely na opÄ›rce.', 'ChyĹĄte EZ osu nebo jednoruÄŤku a lokty nechte fixovanĂ© na podloĹľce.', 'Zvedejte vĂˇhu nahoru plynule bez odlepenĂ­ paĹľĂ­.', 'NahoĹ™e krĂˇtce zatnÄ›te biceps, ale nepĹ™etÄ›Ĺľujte lokty.', 'SpouĹˇtÄ›jte pomalu dolĹŻ do protaĹľenĂ­.', 'VyhnÄ›te se trhĂˇnĂ­ ze spodnĂ­ pozice.'] },
  { id: 'biceps-5', name: 'Cable Curls', equipment: 'Kladka', primaryMuscles: ['biceps'], difficulty: 'easy', instructions: ['Nastavte kladku dole a chyĹĄte rovnou tyÄŤ nebo lano.', 'Postavte se rovnÄ›, lokty drĹľte u tÄ›la a ramena dole.', 'TĂˇhnÄ›te nahoru do ohybu loktĹŻ a drĹľte konstantnĂ­ napÄ›tĂ­.', 'NahoĹ™e krĂˇtce zatnÄ›te biceps a nepouĹˇtÄ›jte lokty dopĹ™edu.', 'PomalĂ˝m pohybem vraĹĄte zpÄ›t dolĹŻ do nataĹľenĂ­.', 'UdrĹľujte plynulĂ˝ rytmus a bez Ĺˇvihu.'] },
  { id: 'biceps-6', name: 'Biceps Builder 6', equipment: 'Stroj', primaryMuscles: ['biceps'], difficulty: 'easy', instructions: ['Nastavte vychozi pozici stroje.', 'Provadejte kontrolovany pohyb v plnem rozsahu.', 'Vracejte se pomalu bez trhani.', 'Drzte stabilni trup a plynuly dech.'] },
  { id: 'biceps-7', name: 'Biceps Focus 7', equipment: 'Jednorucky', primaryMuscles: ['biceps'], difficulty: 'medium', instructions: ['Zvolte primerenou zatez pro cisty pohyb.', 'Provedte koncentrickou fazi s vydechem.', 'Excentrickou fazi zpomalte na 2 az 3 sekundy.', 'Po celou dobu drzte techniku bez kompenzaci.'] },
  { id: 'biceps-8', name: 'Biceps Builder 8', equipment: 'Stroj', primaryMuscles: ['biceps'], difficulty: 'easy', instructions: ['Nastavte vychozi pozici.', 'Provadejte kontrolovany pohyb.', 'Vracejte se pomalu bez trhani.', 'Drzte stabilni trup a plynuly dech.'] },
  { id: 'biceps-9', name: 'Biceps Builder 9', equipment: 'Jednorucky', primaryMuscles: ['biceps'], difficulty: 'medium', instructions: ['Nastavte vychozi pozici.', 'Provadejte kontrolovany pohyb.', 'Vracejte se pomalu bez trhani.', 'Drzte stabilni trup a plynuly dech.'] },
];

export default BICEPS;

