// Data: seznam cvikĹŻ pro partii â€žbĹ™ichoâ€ś.

import { Exercise } from '@/src/data/types';

const ABS: Exercise[] = [{ id: 'abs-1', name: 'Crunches', equipment: 'VlastnĂ­ vĂˇha', primaryMuscles: ['abs'], difficulty: 'easy', instructions: ['LehnÄ›te si na zĂˇda, pokrÄŤte kolena a chodidla poloĹľte na zem.', 'Ruce dejte na hrudnĂ­k nebo lehce za hlavu (netlaÄŤte hlavou dopĹ™edu).', 'ZpevnÄ›te bĹ™icho a lehce podsadĹĄe pĂˇnev.', 'S vĂ˝dechem zvednÄ›te lopatky pĂˇr centimetrĹŻ nad zem a dĂ­vejte se Ĺˇikmo ke kolenĹŻm.', 'Chvilku zatnÄ›te bĹ™icho a pomalu se vraĹĄte zpÄ›t bez â€žplĂˇcnutĂ­â€ś.', 'DrĹľte plynulĂ© tempo a neprohĂ˝bejte bedra.'] },
  { id: 'abs-2', name: 'Plank', equipment: 'VlastnĂ­ vĂˇha', primaryMuscles: ['core'], difficulty: 'easy', instructions: ['OpĹ™ete se o pĹ™edloktĂ­, lokty dejte pĹ™Ă­mo pod ramena.', 'Nohy natĂˇhnÄ›te dozadu a postavte se na ĹˇpiÄŤky.', 'ZpevnÄ›te bĹ™icho a hĂ˝ĹľdÄ›, tÄ›lo drĹľte v jednĂ© pĹ™Ă­mce.', 'NetlaÄŤte ramena k uĹˇĂ­m a drĹľte krk dlouhĂ˝.', 'DĂ˝chejte plynule a kontrolujte, aby se boky nepropadaly.', 'UkonÄŤete sĂ©rii, jakmile ztratĂ­te pevnou pozici.'] },
  { id: 'abs-3', name: 'Leg Raises', equipment: 'VlastnĂ­ vĂˇha', primaryMuscles: ['abs'], difficulty: 'medium', instructions: ['LehnÄ›te si na zĂˇda, ruce dejte podĂ©l tÄ›la nebo pod hĂ˝ĹľdÄ› pro oporu.', 'ZpevnÄ›te stĹ™ed tÄ›la a pĹ™itlaÄŤte bedra k podloĹľce.', 'S vĂ˝dechem zvedejte nataĹľenĂ© nohy nahoru (nebo pokrÄŤenĂ©, pokud je to tÄ›ĹľkĂ©).', 'Zastavte, kdyĹľ cĂ­tĂ­te, Ĺľe se bedra zaÄŤĂ­najĂ­ odlepovat od zemÄ›.', 'Pomalu spouĹˇtÄ›jte dolĹŻ bez Ĺˇvihu a bez prohnutĂ­ v bedrech.', 'Opakujte plynule a kontrolovanÄ›.'] },
  { id: 'abs-4', name: 'Russian Twists', equipment: 'VlastnĂ­ vĂˇha/medicinbal', primaryMuscles: ['obliques'], difficulty: 'easy', instructions: ['SednÄ›te si na zem, mĂ­rnÄ› pokrÄŤte kolena a zakloĹte trup dozadu.', 'ZpevnÄ›te bĹ™icho a drĹľte rovnĂˇ zĂˇda (nehrbte se).', 'ZvednÄ›te chodidla lehce nad zem nebo je nechte na zemi pro jednoduĹˇĹˇĂ­ variantu.', 'OtĂˇÄŤejte trupem doprava a doleva â€“ pohyb vychĂˇzĂ­ z trupu, ne jen z rukou.', 'UdrĹľujte tempo pod kontrolou a nedÄ›lejte rychlĂ© â€žtrhĂˇnĂ­â€ś.', 'Pokud pouĹľĂ­vĂˇte zĂˇtÄ›Ĺľ, drĹľte ji blĂ­zko tÄ›la.'] },
  { id: 'abs-5', name: 'Hanging Knee Raises', equipment: 'Hrazda', primaryMuscles: ['abs'], difficulty: 'medium', instructions: ['ChyĹĄte se hrazdy a nechte se volnÄ› viset s pevnĂ˝mi Ăşchopy.', 'Aktivujte ramena (lehce stĂˇhnÄ›te lopatky dolĹŻ) a zpevnÄ›te stĹ™ed tÄ›la.', 'S vĂ˝dechem zvedejte pokrÄŤenĂˇ kolena smÄ›rem k hrudi.', 'VyhnÄ›te se Ĺˇvihu â€“ pohyb zaÄŤĂ­nejte z bĹ™icha, ne z nohou.', 'Pomalu spouĹˇtÄ›jte zpÄ›t do vĂ˝chozĂ­ pozice a drĹľte kontrolu.', 'Pokud se houpete, zkraĹĄte rozsah a zpomalte.'] },
  { id: 'abs-6', name: 'Abs Builder 6', equipment: 'Stroj', primaryMuscles: ['abs'], difficulty: 'easy', instructions: ['Nastavte vychozi pozici stroje.', 'Provadejte kontrolovany pohyb v plnem rozsahu.', 'Vracejte se pomalu bez trhani.', 'Drzte stabilni trup a plynuly dech.'] },
  { id: 'abs-7', name: 'Abs Focus 7', equipment: 'Jednorucky', primaryMuscles: ['abs'], difficulty: 'medium', instructions: ['Zvolte primerenou zatez pro cisty pohyb.', 'Provedte koncentrickou fazi s vydechem.', 'Excentrickou fazi zpomalte na 2 az 3 sekundy.', 'Po celou dobu drzte techniku bez kompenzaci.'] },
  { id: 'abs-8', name: 'Abs Builder 8', equipment: 'Stroj', primaryMuscles: ['abs'], difficulty: 'easy', instructions: ['Nastavte vychozi pozici.', 'Provadejte kontrolovany pohyb.', 'Vracejte se pomalu bez trhani.', 'Drzte stabilni trup a plynuly dech.'] },
  { id: 'abs-9', name: 'Abs Builder 9', equipment: 'Jednorucky', primaryMuscles: ['abs'], difficulty: 'medium', instructions: ['Nastavte vychozi pozici.', 'Provadejte kontrolovany pohyb.', 'Vracejte se pomalu bez trhani.', 'Drzte stabilni trup a plynuly dech.'] },
];

export default ABS;

