// Data: seznam cvikĹŻ pro partii â€žtricepsâ€ś.

import { Exercise } from '@/src/data/types';

const TRICEPS: Exercise[] = [{ id: 'triceps-1', name: 'Skull Crushers', equipment: 'ÄŚinka', primaryMuscles: ['triceps'], difficulty: 'medium', instructions: ['LehnÄ›te si na laviÄŤku a ÄŤinku drĹľte nad hrudnĂ­kem.', 'Lokty drĹľte nad rameny a zpevnÄ›te lopatky.', 'SpouĹˇtÄ›jte ÄŤinku smÄ›rem k ÄŤelu (nebo lehce za hlavu) pouze ohybem v loktech.', 'Nenechte lokty utĂ­kat do stran.', 'S vĂ˝dechem narovnejte paĹľe zpÄ›t do startu.', 'PouĹľijte kontrolovanĂ© tempo a nepĹ™etÄ›Ĺľujte lokty.'] },
  { id: 'triceps-2', name: 'Close-grip Bench Press', equipment: 'ÄŚinka, lavice', primaryMuscles: ['triceps','chest'], difficulty: 'medium', instructions: ['LehnÄ›te si na laviÄŤku, lopatky stĂˇhnÄ›te k sobÄ› a chodidla na zem.', 'Uchopte osu uĹľĹˇĂ­m Ăşchopem (cca na ĹˇĂ­Ĺ™ku ramen).', 'SpusĹĄte ÄŤinku na stĹ™ed hrudnĂ­ku s lokty blĂ­Ĺľ k tÄ›lu.', 'S vĂ˝dechem vytlaÄŤte ÄŤinku nahoru bez zamykĂˇnĂ­ ramen.', 'DrĹľte zĂˇpÄ›stĂ­ rovnÄ› a neodrĂˇĹľejte ÄŤinku od hrudnĂ­ku.', 'ZaÄŤnÄ›te lehÄŤĂ­ vĂˇhou, technika je dĹŻleĹľitÄ›jĹˇĂ­.'] },
  { id: 'triceps-3', name: 'Triceps Pushdown', equipment: 'Kladka', primaryMuscles: ['triceps'], difficulty: 'easy', instructions: ['Nastavte kladku nahoĹ™e a chyĹĄte tyÄŤ nebo lano.', 'Postavte se stabilnÄ›, lokty drĹľte u tÄ›la a ramena dole.', 'S vĂ˝dechem tlaÄŤte dolĹŻ do propnutĂ­ loktĹŻ.', 'NahoĹ™e nehĂ˝bejte rameny â€“ pracuje pouze loket.', 'Pomalu vraĹĄte zpÄ›t nahoru do ohybu, ale neztrĂˇcejte kontrolu.', 'V hornĂ­ pozici neodpoÄŤĂ­vejte â€“ drĹľte napÄ›tĂ­.'] },
  { id: 'triceps-4', name: 'Overhead Triceps Extension', equipment: 'JednoruÄŤka', primaryMuscles: ['triceps'], difficulty: 'medium', instructions: ['Postavte se nebo si sednÄ›te, jednoruÄŤku drĹľte obÄ›ma rukama nad hlavou.', 'ZpevnÄ›te bĹ™icho a drĹľte Ĺľebra dole.', 'SpouĹˇtÄ›jte jednoruÄŤku za hlavu pouze ohybem v loktech.', 'Lokty drĹľte co nejvĂ­c u sebe a nemÄ›Ĺte pozici ramen.', 'S vĂ˝dechem vytlaÄŤte zpÄ›t nahoru do propnutĂ­.', 'PouĹľijte kontrolovanĂ© tempo a nepĹ™ehĂˇnÄ›jte rozsah.'] },
  { id: 'triceps-5', name: 'Dips (Triceps variant)', equipment: 'ParalelnĂ­ bradla', primaryMuscles: ['triceps'], difficulty: 'medium', instructions: ['ChyĹĄte bradla a zvednÄ›te se do opory s trupem vĂ­ce vzpĹ™Ă­menÄ›.', 'Lokty veÄŹte blĂ­zko tÄ›la a ramena drĹľte dole.', 'SpouĹˇtÄ›jte se dolĹŻ kontrolovanÄ› do pohodlnĂ© hloubky.', 'Zastavte dĹ™Ă­v, pokud cĂ­tĂ­te tlak v pĹ™ednĂ­ ÄŤĂˇsti ramene.', 'VytlaÄŤte se zpÄ›t nahoru s vĂ˝dechem do propnutĂ­.', 'UdrĹľujte stabilnĂ­ trup bez kymĂˇcenĂ­.'] },
  { id: 'triceps-6', name: 'Triceps Builder 6', equipment: 'Stroj', primaryMuscles: ['triceps'], difficulty: 'easy', instructions: ['Nastavte vychozi pozici stroje.', 'Provadejte kontrolovany pohyb v plnem rozsahu.', 'Vracejte se pomalu bez trhani.', 'Drzte stabilni trup a plynuly dech.'] },
  { id: 'triceps-7', name: 'Triceps Focus 7', equipment: 'Jednorucky', primaryMuscles: ['triceps'], difficulty: 'medium', instructions: ['Zvolte primerenou zatez pro cisty pohyb.', 'Provedte koncentrickou fazi s vydechem.', 'Excentrickou fazi zpomalte na 2 az 3 sekundy.', 'Po celou dobu drzte techniku bez kompenzaci.'] },
  { id: 'triceps-8', name: 'Triceps Builder 8', equipment: 'Stroj', primaryMuscles: ['triceps'], difficulty: 'easy', instructions: ['Nastavte vychozi pozici.', 'Provadejte kontrolovany pohyb.', 'Vracejte se pomalu bez trhani.', 'Drzte stabilni trup a plynuly dech.'] },
  { id: 'triceps-9', name: 'Triceps Builder 9', equipment: 'Jednorucky', primaryMuscles: ['triceps'], difficulty: 'medium', instructions: ['Nastavte vychozi pozici.', 'Provadejte kontrolovany pohyb.', 'Vracejte se pomalu bez trhani.', 'Drzte stabilni trup a plynuly dech.'] },
];

export default TRICEPS;

