// Data: seznam cvikĹŻ pro partii â€žkvadricepsâ€ś (pĹ™ednĂ­ stehno).

import { Exercise } from '@/src/data/types';

const QUADRICEPS: Exercise[] = [{ id: 'quadriceps-1', name: 'Squat', equipment: 'ÄŚinka', primaryMuscles: ['quadriceps'], difficulty: 'medium', instructions: ['Postavte se na ĹˇĂ­Ĺ™ku ramen a zpevnÄ›te stĹ™ed tÄ›la.', 'NadechnÄ›te se do bĹ™icha a jdÄ›te dolĹŻ â€“ kolena ve smÄ›ru ĹˇpiÄŤek.', 'UdrĹľujte hrudnĂ­k nahoĹ™e a zĂˇda v neutrĂˇlnĂ­ pozici.', 'Klesejte do hloubky, kterou zvlĂˇdnete bez ztrĂˇty techniky.', 'Z dolnĂ­ pozice se zvedejte tlakem pĹ™es celĂˇ chodidla.', 'Nehoupejte se a neklaÄŹte paty od zemÄ›.'] },
  { id: 'quadriceps-2', name: 'Leg Press', equipment: 'Stroj', primaryMuscles: ['quadriceps'], difficulty: 'medium', instructions: ['Nastavte sed tak, aby spodnĂ­ pozice byla pohodlnĂˇ a bezpeÄŤnĂˇ.', 'Chodidla poloĹľte na platformu (cca na ĹˇĂ­Ĺ™ku ramen).', 'OdemknÄ›te bezpeÄŤnostnĂ­ zarĂˇĹľky a spusĹĄte platformu dolĹŻ kontrolovanÄ›.', 'Klesejte, dokud nepĹ™estĂˇvĂˇte drĹľet pĂˇnev a bedra stabilnĂ­.', 'VytlaÄŤte platformu nahoru bez zamykĂˇnĂ­ kolen.', 'UdrĹľujte plynulĂ© tempo a neodrĂˇĹľejte se ze spodnĂ­ pozice.'] },
  { id: 'quadriceps-3', name: 'Lunges', equipment: 'VlastnĂ­ vĂˇha/JednoruÄŤky', primaryMuscles: ['quadriceps'], difficulty: 'easy', instructions: ['Postavte se rovnÄ› a zpevnÄ›te bĹ™icho.', 'UdÄ›lejte krok vpĹ™ed a spouĹˇtÄ›jte se dolĹŻ do vĂ˝padu.', 'ZadnĂ­ koleno smÄ›Ĺ™uje k zemi, pĹ™ednĂ­ koleno drĹľte ve smÄ›ru ĹˇpiÄŤky.', 'PĹ™ednĂ­ patu drĹľte na zemi a tlakem pĹ™es ni se vraĹĄte zpÄ›t nahoru.', 'Opakujte na stejnou nohu nebo stĹ™Ă­dejte strany.', 'DrĹľte rovnovĂˇhu a nepadĂˇvejte dopĹ™edu.'] },
  { id: 'quadriceps-4', name: 'Leg Extension', equipment: 'Stroj', primaryMuscles: ['quadriceps'], difficulty: 'easy', instructions: ['Nastavte sed tak, aby osa stroje byla v Ăşrovni kolen.', 'OpÄ›rku dejte nad nĂˇrt a chyĹĄte se madel.', 'ZpevnÄ›te trup a plynule natahujte kolena do zvednutĂ­.', 'NahoĹ™e krĂˇtce zatnÄ›te kvadricepsy.', 'Pomalu spouĹˇtÄ›jte dolĹŻ do nataĹľenĂ­ bez â€žpadnutĂ­â€ś.', 'DrĹľte kontrolu a nepĹ™etÄ›Ĺľujte kloub v hornĂ­ pozici.'] },
  { id: 'quadriceps-5', name: 'Bulgarian Split Squat', equipment: 'JednoruÄŤky', primaryMuscles: ['quadriceps','gluteal'], difficulty: 'hard', instructions: ['Postavte se pĹ™ed laviÄŤku, zadnĂ­ nĂˇrt opĹ™ete o laviÄŤku.', 'Pro vĂ­ce kvadricepsĹŻ drĹľte trup o nÄ›co vzpĹ™Ă­menÄ›jĹˇĂ­.', 'Klesejte dolĹŻ kontrolovanÄ›, pĹ™ednĂ­ koleno smÄ›Ĺ™uje ve smÄ›ru ĹˇpiÄŤky.', 'UdrĹľujte stabilnĂ­ pĂˇnev a nevyboÄŤujte kolenem dovnitĹ™.', 'VytlaÄŤte se nahoru tlakem pĹ™es celou plosku pĹ™ednĂ­ nohy.', 'ZaÄŤnÄ›te bez velkĂ© zĂˇtÄ›Ĺľe a pĹ™idĂˇvejte postupnÄ›.'] },
  { id: 'quadriceps-6', name: 'Quadriceps Builder 6', equipment: 'Stroj', primaryMuscles: ['quadriceps'], difficulty: 'easy', instructions: ['Nastavte vychozi pozici stroje.', 'Provadejte kontrolovany pohyb v plnem rozsahu.', 'Vracejte se pomalu bez trhani.', 'Drzte stabilni trup a plynuly dech.'] },
  { id: 'quadriceps-7', name: 'Quadriceps Focus 7', equipment: 'Jednorucky', primaryMuscles: ['quadriceps'], difficulty: 'medium', instructions: ['Zvolte primerenou zatez pro cisty pohyb.', 'Provedte koncentrickou fazi s vydechem.', 'Excentrickou fazi zpomalte na 2 az 3 sekundy.', 'Po celou dobu drzte techniku bez kompenzaci.'] },
  { id: 'quadriceps-8', name: 'Quadriceps Builder 8', equipment: 'Stroj', primaryMuscles: ['quadriceps'], difficulty: 'easy', instructions: ['Nastavte vychozi pozici.', 'Provadejte kontrolovany pohyb.', 'Vracejte se pomalu bez trhani.', 'Drzte stabilni trup a plynuly dech.'] },
  { id: 'quadriceps-9', name: 'Quadriceps Builder 9', equipment: 'Jednorucky', primaryMuscles: ['quadriceps'], difficulty: 'medium', instructions: ['Nastavte vychozi pozici.', 'Provadejte kontrolovany pohyb.', 'Vracejte se pomalu bez trhani.', 'Drzte stabilni trup a plynuly dech.'] },
];

export default QUADRICEPS;

