// Data: seznam cvikĹŻ pro partii â€žhĂ˝ĹľdÄ›â€ś.

import { Exercise } from '@/src/data/types';

const GLUTEAL: Exercise[] = [{ id: 'gluteal-1', name: 'Hip Thrust', equipment: 'Lavice, ÄŤinka', primaryMuscles: ['gluteal'], difficulty: 'medium', instructions: ['OpĹ™ete hornĂ­ ÄŤĂˇst zad o laviÄŤku a ÄŤinku poloĹľte pĹ™es pĂˇnev (pouĹľijte podloĹľku).', 'Chodidla dejte na ĹˇĂ­Ĺ™ku bokĹŻ a zpevnÄ›te bĹ™icho.', 'S vĂ˝dechem tlaÄŤte boky vzhĹŻru tak, aby trup byl v hornĂ­ pozici zhruba vodorovnÄ›.', 'V hornĂ­ pozici krĂˇtce zatnÄ›te hĂ˝ĹľdÄ› a lehce podsadĹĄe pĂˇnev.', 'Pomalu spouĹˇtÄ›jte dolĹŻ do vĂ˝chozĂ­ pozice bez â€žpadnutĂ­â€ś.', 'KolenĹŻm drĹľte smÄ›r ven (nebojte se je lehce tlaÄŤit od sebe).'] },
  { id: 'gluteal-2', name: 'Glute Bridge', equipment: 'VlastnĂ­ vĂˇha', primaryMuscles: ['gluteal'], difficulty: 'easy', instructions: ['LehnÄ›te si na zĂˇda, pokrÄŤte kolena a chodidla poloĹľte na zem.', 'Chodidla dejte cca pod kolena a zpevnÄ›te bĹ™icho.', 'S vĂ˝dechem zvedejte boky vzhĹŻru, tlaÄŤte pĹ™es paty.', 'NahoĹ™e zatnÄ›te hĂ˝ĹľdÄ› a nedovolte prohnutĂ­ v bedrech.', 'Pomalu se vraĹĄte dolĹŻ do vĂ˝chozĂ­ pozice.', 'Pro tÄ›ĹľĹˇĂ­ variantu podrĹľte nahoĹ™e 1â€“2 sekundy.'] },
  { id: 'gluteal-3', name: 'Bulgarian Split Squat', equipment: 'JednoruÄŤky', primaryMuscles: ['gluteal','quadriceps'], difficulty: 'hard', instructions: ['Postavte se pĹ™ed laviÄŤku a zadnĂ­ nĂˇrt opĹ™ete o laviÄŤku.', 'PĹ™ednĂ­ nohu dejte tak daleko, aby koleno mohlo jĂ­t dolĹŻ bez ztrĂˇty rovnovĂˇhy.', 'ZpevnÄ›te stĹ™ed tÄ›la a klesejte dolĹŻ kontrolovanÄ›.', 'PĹ™ednĂ­ koleno drĹľte ve smÄ›ru ĹˇpiÄŤky a patu pĹ™ednĂ­ nohy neodlepujte.', 'Z dolnĂ­ pozice se zvednÄ›te tlakem pĹ™es celou plosku pĹ™ednĂ­ nohy.', 'DrĹľte stabilnĂ­ tempo a neodrĂˇĹľejte se.'] },
  { id: 'gluteal-4', name: 'Single-leg Romanian Deadlift', equipment: 'JednoruÄŤky', primaryMuscles: ['gluteal','hamstrings'], difficulty: 'medium', instructions: ['Postavte se na jednu nohu, druhou nohu lehce zvednÄ›te dozadu.', 'ZpevnÄ›te bĹ™icho a drĹľte pĂˇnev â€žrovnÄ›â€ś (neotĂˇÄŤejte ji do strany).', 'JdÄ›te do pĹ™edklonu (hinge) a posĂ­lejte boky dozadu.', 'ZĂˇtÄ›Ĺľ drĹľte blĂ­zko nohy a zĂˇda drĹľte v neutrĂˇlu.', 'Zastavte v pozici, kde cĂ­tĂ­te protaĹľenĂ­ zadnĂ­ strany stehna.', 'VraĹĄte se nahoru zataĹľenĂ­m hĂ˝ĹľdÄ› a hamstringu â€“ bez Ĺˇvihu.'] },
  { id: 'gluteal-5', name: 'Cable Kickbacks', equipment: 'Kladka', primaryMuscles: ['gluteal'], difficulty: 'easy', instructions: ['PĹ™ipevnÄ›te popruh na kotnĂ­k a postavte se ÄŤelem ke kladce.', 'OpĹ™ete se rukama a zpevnÄ›te stĹ™ed tÄ›la.', 'KopnÄ›te nohou dozadu a nahoru v kontrolovanĂ©m rozsahu.', 'V hornĂ­ pozici krĂˇtce zatnÄ›te hĂ˝ĹľdÄ›.', 'Pomalu vraĹĄte nohu zpÄ›t bez prohnutĂ­ v bedrech.', 'NetoÄŤte trupem â€“ pohyb jde z kyÄŤle.'] },
  { id: 'gluteal-6', name: 'Gluteal Builder 6', equipment: 'Stroj', primaryMuscles: ['gluteal'], difficulty: 'easy', instructions: ['Nastavte vychozi pozici stroje.', 'Provadejte kontrolovany pohyb v plnem rozsahu.', 'Vracejte se pomalu bez trhani.', 'Drzte stabilni trup a plynuly dech.'] },
  { id: 'gluteal-7', name: 'Gluteal Focus 7', equipment: 'Jednorucky', primaryMuscles: ['gluteal'], difficulty: 'medium', instructions: ['Zvolte primerenou zatez pro cisty pohyb.', 'Provedte koncentrickou fazi s vydechem.', 'Excentrickou fazi zpomalte na 2 az 3 sekundy.', 'Po celou dobu drzte techniku bez kompenzaci.'] },
  { id: 'gluteal-8', name: 'Gluteal Builder 8', equipment: 'Stroj', primaryMuscles: ['gluteal'], difficulty: 'easy', instructions: ['Nastavte vychozi pozici.', 'Provadejte kontrolovany pohyb.', 'Vracejte se pomalu bez trhani.', 'Drzte stabilni trup a plynuly dech.'] },
  { id: 'gluteal-9', name: 'Gluteal Builder 9', equipment: 'Jednorucky', primaryMuscles: ['gluteal'], difficulty: 'medium', instructions: ['Nastavte vychozi pozici.', 'Provadejte kontrolovany pohyb.', 'Vracejte se pomalu bez trhani.', 'Drzte stabilni trup a plynuly dech.'] },
];

export default GLUTEAL;

