// Data: seznam cvikĹŻ pro partii â€žzĂˇdaâ€ś.

import { Exercise } from '@/src/data/types';

const BACK: Exercise[] = [{ id: 'back-1', name: 'Deadlift', equipment: 'ÄŚinka', primaryMuscles: ['back'], difficulty: 'hard', instructions: ['Postavte se na ĹˇĂ­Ĺ™ku bokĹŻ, ÄŤinka nad stĹ™edem chodidel.', 'ChyĹĄte osu, zpevnÄ›te stĹ™ed tÄ›la a srovnejte zĂˇda do neutrĂˇlu.', 'ZatlaÄŤte chodidly do zemÄ› a zvedejte ÄŤinku s osou co nejblĂ­Ĺľ u tÄ›la.', 'V hornĂ­ pozici se narovnejte bez zbyteÄŤnĂ©ho zĂˇklonu.', 'SpouĹˇtÄ›jte kontrolovanÄ› zpÄ›t dolĹŻ stejnou drĂˇhou.', 'Pokud se vĂˇm kulatĂ­ zĂˇda, sniĹľte vĂˇhu nebo rozsah.'] },
  { id: 'back-2', name: 'Pull-ups', equipment: 'Hrazda', primaryMuscles: ['upper-back','lats'], difficulty: 'hard', instructions: ['ChyĹĄte hrazdu nadhmatem nebo shybem a povÄ›ste se do plnĂ©ho visu.', 'ZaÄŤnÄ›te pohyb staĹľenĂ­m lopatek dolĹŻ a dozadu (ne ramena k uĹˇĂ­m).', 'TĂˇhnÄ›te hrudnĂ­k smÄ›rem k hrazdÄ› a lokty veÄŹte dolĹŻ k bokĹŻm.', 'NahoĹ™e krĂˇtce zpevnÄ›te zĂˇda a drĹľte tÄ›lo bez houpĂˇnĂ­.', 'Pomalu se spusĹĄte zpÄ›t do plnĂ©ho visu.', 'Pokud je to tÄ›ĹľkĂ©, pouĹľijte gumu nebo asistovanĂ˝ stroj.'] },
  { id: 'back-3', name: 'Bent Over Row', equipment: 'ÄŚinka', primaryMuscles: ['upper-back'], difficulty: 'medium', instructions: ['Postavte se, uchopte ÄŤinku a jdÄ›te do pĹ™edklonu (hinge) se rovnĂ˝mi zĂˇdy.', 'Kolena mĂ­rnÄ› pokrÄŤte, bĹ™icho zpevnÄ›te a drĹľte neutrĂˇlnĂ­ pĂˇteĹ™.', 'TĂˇhnÄ›te ÄŤinku k spodnĂ­m ĹľebrĹŻm / bĹ™ichu a lokty veÄŹte podĂ©l tÄ›la.', 'NahoĹ™e stĂˇhnÄ›te lopatky k sobÄ› a dolĹŻ.', 'SpouĹˇtÄ›jte ÄŤinku pomalu a nenechte ramena â€žvyjetâ€ś dopĹ™edu.', 'NepouĹľĂ­vejte Ĺˇvih â€“ radÄ›ji sniĹľte vĂˇhu.'] },
  { id: 'back-4', name: 'Lat Pulldown', equipment: 'Kladka', primaryMuscles: ['lats'], difficulty: 'medium', instructions: ['Nastavte si sed a opÄ›rku na stehna, aby vĂˇs â€žnezvedaloâ€ś ze sedaÄŤky.', 'ChyĹĄte tyÄŤ o nÄ›co ĹˇirĹˇĂ­ neĹľ ramena a trup drĹľte vzpĹ™Ă­menÄ›.', 'ZaÄŤnÄ›te staĹľenĂ­m lopatek dolĹŻ a potĂ© tĂˇhnÄ›te tyÄŤ k hornĂ­ ÄŤĂˇsti hrudnĂ­ku.', 'Lokty veÄŹte dolĹŻ a lehce dozadu, ne dopĹ™edu.', 'Pomalu vraĹĄte tyÄŤ nahoru do nataĹľenĂ­ bez trhĂˇnĂ­.', 'DrĹľte kontrolu a neprohĂ˝bejte se v bedrech.'] },
  { id: 'back-5', name: 'Seated Cable Row', equipment: 'Kladka', primaryMuscles: ['middle-back'], difficulty: 'medium', instructions: ['SednÄ›te si, chodidla opĹ™ete o platformu a chyĹĄte rukojeĹĄ.', 'Narovnejte zĂˇda a zpevnÄ›te bĹ™icho â€“ ĹľĂˇdnĂ© hrbenĂ­.', 'TĂˇhnÄ›te rukojeĹĄ k pasu a souÄŤasnÄ› stahujte lopatky k sobÄ›.', 'NahoĹ™e krĂˇtce zastavte a drĹľte ramena dole.', 'PomalĂ˝m pohybem vraĹĄte rukojeĹĄ dopĹ™edu do protaĹľenĂ­ zad.', 'UdrĹľujte stejnĂ˝ Ăşhel trupu po celĂ˝ pohyb.'] },
  { id: 'back-6', name: 'Back Builder 6', equipment: 'Stroj', primaryMuscles: ['back'], difficulty: 'easy', instructions: ['Nastavte vychozi pozici stroje.', 'Provadejte kontrolovany pohyb v plnem rozsahu.', 'Vracejte se pomalu bez trhani.', 'Drzte stabilni trup a plynuly dech.'] },
  { id: 'back-7', name: 'Back Focus 7', equipment: 'Jednorucky', primaryMuscles: ['back'], difficulty: 'medium', instructions: ['Zvolte primerenou zatez pro cisty pohyb.', 'Provedte koncentrickou fazi s vydechem.', 'Excentrickou fazi zpomalte na 2 az 3 sekundy.', 'Po celou dobu drzte techniku bez kompenzaci.'] },
  { id: 'back-8', name: 'Back Builder 8', equipment: 'Stroj', primaryMuscles: ['back'], difficulty: 'easy', instructions: ['Nastavte vychozi pozici.', 'Provadejte kontrolovany pohyb.', 'Vracejte se pomalu bez trhani.', 'Drzte stabilni trup a plynuly dech.'] },
  { id: 'back-9', name: 'Back Builder 9', equipment: 'Jednorucky', primaryMuscles: ['back'], difficulty: 'medium', instructions: ['Nastavte vychozi pozici.', 'Provadejte kontrolovany pohyb.', 'Vracejte se pomalu bez trhani.', 'Drzte stabilni trup a plynuly dech.'] },
];

export default BACK;

