// Data: seznam cvikĹŻ pro partii â€žtrapĂ©zyâ€ś (trapezius).

import { Exercise } from '@/src/data/types';

const TRAPEZIUS: Exercise[] = [{ id: 'trapezius-1', name: 'Shrugs', equipment: 'ÄŚinka/ jednoruÄŤky', primaryMuscles: ['trapezius'], difficulty: 'easy', instructions: ['Postavte se rovnÄ› a drĹľte zĂˇtÄ›Ĺľ podĂ©l tÄ›la.', 'ZpevnÄ›te bĹ™icho a drĹľte ramena â€ždoleâ€ś v neutrĂˇlu.', 'ZvednÄ›te ramena pĹ™Ă­mo nahoru smÄ›rem k uĹˇĂ­m (bez krouĹľenĂ­).', 'NahoĹ™e krĂˇtce zatnÄ›te trapĂ©zy.', 'Pomalu spusĹĄte zpÄ›t dolĹŻ do vĂ˝chozĂ­ pozice.', 'Hlavu drĹľte rovnÄ› a neprohĂ˝bejte krk.'] },
  { id: 'trapezius-2', name: 'Face Pulls', equipment: 'Kladka', primaryMuscles: ['trapezius','rear-delts'], difficulty: 'medium', instructions: ['Nastavte kladku na hornĂ­ pozici a chyĹĄte lano.', 'Postavte se stabilnÄ› a zpevnÄ›te stĹ™ed tÄ›la.', 'ZaÄŤnÄ›te staĹľenĂ­m lopatek dozadu a dolĹŻ.', 'TĂˇhnÄ›te lano k obliÄŤeji, lokty veÄŹte vysoko do stran.', 'V konci pohybu lehce â€žroztrhnÄ›teâ€ś lano a zatnÄ›te zadnĂ­ delty.', 'Pomalu vraĹĄte zpÄ›t bez vytaĹľenĂ­ ramen k uĹˇĂ­m.'] },
  { id: 'trapezius-3', name: 'Upright Row', equipment: 'ÄŚinka', primaryMuscles: ['trapezius'], difficulty: 'medium', instructions: ['Postavte se rovnÄ› a drĹľte ÄŤinku nadhmatem na ĹˇĂ­Ĺ™ku ramen.', 'ZpevnÄ›te bĹ™icho a drĹľte ramena dole.', 'TĂˇhnÄ›te ÄŤinku vzhĹŻru podĂ©l tÄ›la, lokty veÄŹte vĂ˝Ĺˇ neĹľ zĂˇpÄ›stĂ­.', 'Zvedejte do pohodlnĂ© vĂ˝Ĺˇky (nenĂ­ nutnĂ© aĹľ k bradÄ›).', 'Pomalu spouĹˇtÄ›jte zpÄ›t dolĹŻ bez trhĂˇnĂ­.', 'Pokud cĂ­tĂ­te nepohodlĂ­ v ramenou, zkraĹĄte rozsah nebo zvolte jinĂ˝ cvik.'] },
  { id: 'trapezius-4', name: 'Dumbbell High Pull', equipment: 'JednoruÄŤky', primaryMuscles: ['trapezius'], difficulty: 'medium', instructions: ['Postavte se a drĹľte jednoruÄŤky pĹ™ed tÄ›lem.', 'ZpevnÄ›te stĹ™ed tÄ›la a lehce pokrÄŤte kolena.', 'VyjeÄŹte vĂ˝buĹˇnÄ› nahoru a tĂˇhnÄ›te lokty vysoko do stran.', 'JednoruÄŤky vedou pohyb, ale lokty jsou â€žmotorâ€ś.', 'VraĹĄte se dolĹŻ kontrolovanÄ› a pĹ™ipravte dalĹˇĂ­ opakovĂˇnĂ­.', 'PouĹľijte spĂ­Ĺˇ lehÄŤĂ­ vĂˇhu a ÄŤistĂ˝ pohyb.'] },
  { id: 'trapezius-5', name: 'Barbell Upright Shrug', equipment: 'ÄŚinka', primaryMuscles: ['trapezius'], difficulty: 'medium', instructions: ['Postavte se rovnÄ› a drĹľte ÄŤinku nadhmatem pĹ™ed tÄ›lem.', 'ZpevnÄ›te bĹ™icho a drĹľte krk dlouhĂ˝.', 'ZvednÄ›te ramena nahoru a lehce dozadu, jako byste je chtÄ›li â€žzasunoutâ€ś.', 'NahoĹ™e krĂˇtce zatnÄ›te trapĂ©zy.', 'Pomalu spusĹĄte zpÄ›t dolĹŻ bez krouĹľenĂ­ rameny.', 'DrĹľte pohyb krĂˇtkĂ˝ a kontrolovanĂ˝.'] },
  { id: 'trapezius-6', name: 'Trapezius Builder 6', equipment: 'Stroj', primaryMuscles: ['trapezius'], difficulty: 'easy', instructions: ['Nastavte vychozi pozici stroje.', 'Provadejte kontrolovany pohyb v plnem rozsahu.', 'Vracejte se pomalu bez trhani.', 'Drzte stabilni trup a plynuly dech.'] },
  { id: 'trapezius-7', name: 'Trapezius Focus 7', equipment: 'Jednorucky', primaryMuscles: ['trapezius'], difficulty: 'medium', instructions: ['Zvolte primerenou zatez pro cisty pohyb.', 'Provedte koncentrickou fazi s vydechem.', 'Excentrickou fazi zpomalte na 2 az 3 sekundy.', 'Po celou dobu drzte techniku bez kompenzaci.'] },
  { id: 'trapezius-8', name: 'Trapezius Builder 8', equipment: 'Stroj', primaryMuscles: ['trapezius'], difficulty: 'easy', instructions: ['Nastavte vychozi pozici.', 'Provadejte kontrolovany pohyb.', 'Vracejte se pomalu bez trhani.', 'Drzte stabilni trup a plynuly dech.'] },
  { id: 'trapezius-9', name: 'Trapezius Builder 9', equipment: 'Jednorucky', primaryMuscles: ['trapezius'], difficulty: 'medium', instructions: ['Nastavte vychozi pozici.', 'Provadejte kontrolovany pohyb.', 'Vracejte se pomalu bez trhani.', 'Drzte stabilni trup a plynuly dech.'] },
];

export default TRAPEZIUS;

